name: MMS Auto Notification

on:
  schedule:
    # 設定在台灣時間每個工作日早上 9:30 執行（UTC+8）
    # GitHub Actions 使用 UTC 時間，所以要設定為 UTC 1:30
    - cron: '30 1 * * 1-5'
  
  # 允許手動觸發工作流程
  workflow_dispatch:

jobs:
  run-notification:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run MMS notification script
      env:
        MMS_API_KEY: ${{ secrets.MMS_API_KEY }}
        MMS_BASE_URL: ${{ secrets.MMS_BASE_URL }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: python main.py 