name: MMS Auto Notification

on:
  schedule:
    # 設定在台灣時間每個工作日早上 9:30 執行（UTC+8）
    # GitHub Actions 使用 UTC 時間，所以要設定為 UTC 1:30
    - cron: '30 1 * * 1-5'
  
  # 允許手動觸發工作流程
  workflow_dispatch:

jobs:
  run-notification:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run MMS notification script
      env:
        MMS_API_KEY: ${{ eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbXlhY2NvdW50Lm5hbmkuY29vbC8iLCJzdWIiOiJ1c2Vycy9PTkVXVDAwNjI4IiwiZnJvbSI6Ik5hbmkiLCJ1c2VybmFtZSI6Ik9ORVdUMDA2MjgiLCJlbWFpbHZhbGlkIjp0cnVlLCJtb2JpbGV2YWxpZCI6ZmFsc2UsImVtYWlsIjoibG9vdDg2NTEzQGdtYWlsLmNvbSIsInVpZCI6Ijc5OGU1NTQwLWQ1MzgtMTFlZS04MDhmLTQ5YzkzYjQxMTkyOCIsImp0aSI6IjlmZjQ3MGEzLTQxOTAtNGQ1Mi04MzczLTQxOWEwYjQ4N2M3NyIsImlhdCI6MTc0MTg1NzA4NiwiZXhwIjoxNzQ3MDQxMDg2fQ.DVZlMyXalq6yXcvrtz9nGIXXMsvHkng0IouuZjgwmWU }}
        MMS_BASE_URL: ${{ https://api-new.oneclass.co/mms/proxy/link-plus }}
        SLACK_WEBHOOK_URL: ${{ https://hooks.slack.com/services/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 }}
      run: python main.py 